version: '2'
services:
    php:
        build: php-fpm
        ports:
            - '9002:9000'
        volumes:
            - ../app:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
    nginx:
        build: nginx
        ports:
            - '80:80'
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
            - ../frontend/build/:/var/www/frontend